In [1]:
import pandas as pd

In [2]:
#6.1
sales  = pd.read_csv(r"C:\Users\DELL\Downloads\sales.csv")
houses = pd.read_csv(r"C:\Users\DELL\Downloads\houses.csv")
employees = pd.read_csv(r"C:\Users\DELL\Downloads\employees.csv")

In [9]:
#6.2
employees.loc[3:10][['EMP_FIRST_NAME', 'EMP_LAST_NAME']]

   EMP_FIRST_NAME EMP_LAST_NAME
3          Shelia      Larchier
4           Annie        Jerche
5         Cacilia        Pester
6          Ronica       McAlees
7          Bobina   Hrihorovich
8          Valina      Bestwall
9         Jaynell       Mattedi
10        Andonis        Muress

In [18]:
#6.3
men =  employees[employees['EMP_GENDER']== 'M'].value_counts().shape[0]
women = employees[employees['EMP_GENDER']== 'F'].value_counts().shape[0]
print('men', '---> ', men)
print('women', '---> ', women)

men --->  431
women --->  427

In [20]:
6.4
houses['SQUARE'] = houses['SQUARE'].fillna(0)

In [24]:
#6.5
houses['unit_price'] = round(houses['PRICE']/houses['SQUARE'], 2)

In [26]:
#6.6
houses.sort_values(by = 'PRICE', ascending = False, inplace = True)
houses.to_json(r"C:\Users\DELL\Desktop\epam\pythom_tasks\pythonProject\houses_updated.json")

In [34]:
#6.7
employees[(employees['EMP_GENDER'] == 'F') & (employees['EMP_FIRST_NAME'] == 'Vera')].shape[0]

1

In [37]:
#6.8
houses[houses['SQUARE'] >= 100] .groupby(['HOUSE_CATEGORY', 'HOUSE_SUBCATEGORY']).count()

                                     HOUSE_ID  HOUSE_NAME  HOUSE_CATEGORY_ID  \
HOUSE_CATEGORY  HOUSE_SUBCATEGORY
non-residential office                   1150        1150               1150
                stock                   29644       29641              29644
residential     duplex house            70076       70071              70076
                single-family house     86618       86613              86618

                                     HOUSE_SUBCATEGORY_ID  SQUARE  PRICE  \
HOUSE_CATEGORY  HOUSE_SUBCATEGORY
non-residential office                               1150    1150   1150
                stock                               29644   29644  29644
residential     duplex house                        70076   70076  70076
                single-family house                 86618   86618  86618

                                     LOCATION_ID  UPDATE_DT  unit_price
HOUSE_CATEGORY  HOUSE_SUBCATEGORY
non-residential office                      1150       1150        1150
                stock                      29643      29644       29644
residential     duplex house               70076      70076       70076
                single-family house        86618      86618       86618

In [41]:
#6.9
from pandavro import to_avro
result = houses[houses['SQUARE'] >= 100] .groupby(['HOUSE_CATEGORY', 'HOUSE_SUBCATEGORY']).count()
to_avro("result", result)

In [39]:
pip install pandavro

Collecting pandavroNote: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\ProgramData\anaconda3\Lib\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\ProgramData\anaconda3\Lib\site-packages\~-mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.6 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.4.6 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.6 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.6 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.4.6 which is incompatible.

  Downloading pandavro-1.9.0-py3-none-any.whl.metadata (8.7 kB)
Collecting fastavro<2.0.0,>=1.5.1 (from pandavro)
  Downloading fastavro-1.12.2-cp312-cp312-win_amd64.whl.metadata (6.0 kB)
Requirement already satisfied: pandas<3.0.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from pandavro) (2.2.2)
Collecting numpy<3.0.0,>=2.0 (from pandavro)
  Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.0->pandavro) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.0->pandavro) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.0->pandavro) (2023.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0->pandavro) (1.16.0)
Downloading pandavro-1.9.0-py3-none-any.whl (9.0 kB)
Downloading fastavro-1.12.2-cp312-cp312-win_amd64.whl (441 kB)
Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 2.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/12.3 MB 2.5 MB/s eta 0:00:05
   ------ --------------------------------- 2.1/12.3 MB 2.7 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.3 MB 2.7 MB/s eta 0:00:04
   ----------- ---------------------------- 3.4/12.3 MB 2.8 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.3 MB 2.7 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.3 MB 2.8 MB/s eta 0:00:03
   ---------------- ----------------------- 5.0/12.3 MB 2.8 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.3 MB 2.9 MB/s eta 0:00:03
   --------------------- ------------------ 6.6/12.3 MB 2.9 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.3 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.3 MB 2.9 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 3.0 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.3 MB 3.0 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.3 MB 3.0 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 2.9 MB/s eta 0:00:00
Installing collected packages: numpy, fastavro, pandavro
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Successfully installed fastavro-1.12.2 numpy-2.4.6 pandavro-1.9.0

In [44]:
# 6.10
avg_sale = sales['SALEAMOUNT'].mean()
sales['SALEAMOUNT'] = sales['SALEAMOUNT'] + avg_sale * 0.02

In [45]:
houses

,HOUSE_ID,HOUSE_NAME,HOUSE_CATEGORY_ID,HOUSE_CATEGORY,HOUSE_SUBCATEGORY_ID,HOUSE_SUBCATEGORY,SQUARE,PRICE,LOCATION_ID,UPDATE_DT,unit_price
125512,956321,soft NA2631099,1007,residential,3,duplex house,200.0,558600,954789.0,1-Jan-14,2793.0
88170,762848,low TOR1629826,1007,residential,3,duplex house,200.0,558600,761593.0,1-Jan-14,2793.0
326832,579727,full CU575745,1007,residential,3,duplex house,200.0,558600,578718.0,1-Jan-14,2793.0
495597,901113,far PI1685949 4,1007,residential,3,duplex house,200.0,558600,899611.0,1-Jan-14,2793.0
832442,337278,flat JE2133292 b,1007,residential,3,duplex house,200.0,558600,336635.0,1-Jan-14,2793.0
...,...,...,...,...,...,...,...,...,...,...,...
624676,270487,sweet D802401 b,1008,non-residential,2,universal buildings,16.0,30400,270027.0,1-Jan-14,1900.0
718167,881904,BIG CEDA2027231,1008,non-residential,2,universal buildings,16.0,30400,880460.0,1-Jan-14,1900.0
138159,138294,lucky LA750552,1008,non-residential,2,universal buildings,16.0,30400,138038.0,1-Jan-14,1900.0
686029,952579,hot WOR1966314,1008,non-residential,2,universal buildings,16.0,30400,951047.0,1-Jan-14,1900.0
385713,4774,low ASHF1115719,1008,non-residential,2,universal buildings,16.0,30400,4774.0,1-Jan-14,1900.0

In [48]:
#6.11
house_available = houses.loc[~houses['HOUSE_ID'].isin(sales['HOUSE_ID']), 'HOUSE_ID'].unique().tolist()

pd.Series(house_available).to_json('task_11.json')